version: "3.8"
services:
  flask-app:
    container_name: flask-app
    image: ashqa/flask-app:latest
    build: .
    environment:
      YOUR_NAME: Ashley
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf