version: "3.8"
services:
  mysql:
    container_name: lab9-mysql
    image: backend-db:latest
    build: ./db
    volumes:
    - "db-data:/var/lib/mysql"
  flask-app:
    container_name: lab9-flask
    image: flask-app:latest
    build: ./flask-app
    environment:
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      -  mysql
  nginx:
    container_name: lab9-proxy
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
volumes:
  db-data: